services:
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - UMASK_SET=022
      - WEBUI_PORT=8082
    volumes:
      - ./data/config:/config
      - ./books:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8082
    restart: unless-stopped