services:
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - UMASK_SET=022
      - WEBUI_PORT=8082
    volumes:
      - ./data/config:/config
      - ./books:/downloads
    ports:
      - "8082:8082"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s