services:
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - UMASK_SET=022
      - WEBUI_PORT=8082
    volumes:
      - ./data/config:/config
      - ./books:/downloads
    ports:
      - "8082:8082"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  mariadb:
    image: mariadb:11.8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookmanager
      - MYSQL_USER=bookmanageruser
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "mariadb", "--user=root", "--password=$DB_ROOT_PASSWORD","--database","bookmanager", "-e", "SELECT 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5