services:
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - UMASK_SET=022
      - WEBUI_PORT=8082
    volumes:
      - ./data/config:/config
      - ${BOOK_PATH}:/downloads
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  book_manager:
    image: littleorange666/book_manager:1.1.1
    depends_on:
      qbittorrent:
        condition: service_healthy
    environment:
      - SERVER_PORT=5000
      - WEBUI_HOST=qbittorrent
      - WEBUI_PORT=8082
      - WEBUI_USER=admin
      - WEBUI_PASS=${WEBUI_PASSWORD}
      - ADMIN_KEY=${ADMIN_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ${BOOK_PATH}:/app/books